app/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session, current_app
from app.models import db, Users, Subject, Chapter, Quiz, Question, Score
from werkzeug.security import generate_password_hash,check_password_hash
import os
from datetime import date, datetime, time
import uuid
from functools import wraps

main = Blueprint('main',__name__)

def login_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if 'user_id' not in session:
            flash('Login to start !!','error')
            return redirect(url_for('main.login'))
        return f(*args, **kwargs)
    return decorated_function

def role_required(type):
    def decorator(f):
        @wraps(f)
        def decorated_function(*args, **kwargs):
            if session.get('user_type') != type:
                flash('Unauthorized access', 'error')
                return redirect(url_for('main.login'))
            return f(*args, **kwargs)
        return decorated_function
    return decorator

@main.route('/')
def home():
    return render_template('index.html')

@main.route('/login')
def login_page():
    return render_template('login.html')

@main.route('/login', methods=['POST'])
def login():
    email=request.form['username']
    password=request.form['password']
    if email=='' or password=='':
        flash('Empty Fields !!','error')
        return redirect(url_for('main.login_page'))
    user=Users.query.filter_by(user_mail=email).first()
    if user:
        if check_password_hash(user.user_pass,password):
            session['user_id']=user.user_id
            session['email']=user.user_mail
            session['usename']=user.user_name
            session['user_type']=user.user_type
            session['qualification']=user.qualification
            session['dob']=user.dob
            flash('Login Successful !!','success')
            if user.user_type == 'admin':
                return redirect(url_for('main.admin_homepage'))
            else:
                return redirect(url_for('main.customer_homepage'))

        else:
            flash('Invalid Password !!','error')
            return redirect(url_for('main.login_page'))
    else:
        flash('No user exist with this mail id !!','error')
        return redirect(url_for('main.login_page'))

@main.route('/register')
def register_page():
    return render_template('user_reg.html')

@main.route('/register', methods=['POST'])
def register():
    user_email=request.form['email']
    user_name=request.form['fullname']
    user_pass=request.form['password']
    user_cpass=request.form['cpassword']
    user_qualification=request.form['qualification']
    user_dob=request.form['dob']
    dob = datetime.strptime(user_dob, "%Y-%m-%d").date()

    if user_pass==user_cpass:
        if user_email=="" or user_name=="" or user_pass=="" or user_dob=="":
            flash('Empty Field !!','error')
            return redirect(url_for('main.register_page'))
        else:
            if Users.query.filter_by(user_mail=user_email).first():
                flash('Mail already exists !!','error')
                return redirect(url_for('main.register_page'))

            user_id='C'+ str(uuid.uuid4().hex[:8])

            new_user=Users(user_id=user_id, user_mail=user_email, user_name=user_name, user_type='customer', user_pass=generate_password_hash(user_pass),qualification=user_qualification,dob=dob)
            

            db.session.add(new_user)
            db.session.commit()

            flash('Registeration Successful !!','success')
            return render_template('login.html')
    else:
        flash('Password and Confirm Password should be same !!','error')
        return redirect(url_for('main.register_page'))

@main.route('/admin_home')
@login_required
@role_required('admin')
def admin_homepage():
    user=session['user_id']

    subject_list=Subject.query.all()
    chap=Chapter.query.all()
    user_list=Users.query.all()
    return render_template('admin_home.html',subject_list=subject_list,chap=chap,user_list=user_list)

@main.route('/remove_user/<user>',methods=['POST'])
@login_required
@role_required('admin')
def remove_user(user):
    rm_user=Users.query.filter_by(user_id=user).first()

    db.session.delete(rm_user)
    db.session.commit()
    flash('User removed !!',"success")
    return redirect(request.referrer)

@main.route('/add_subject',methods=['POST'])
@login_required
@role_required('admin')
def add_subject():
    subject_name = request.form['subject_name']
    description = request.form['description']
    id = 'S' + str(uuid.uuid4().hex[:8])

    new_subject = Subject(sub_id=id, sub_name=subject_name, sub_desc=description)
    db.session.add(new_subject)
    db.session.commit()
    
    return redirect(url_for('main.admin_homepage'))

@main.route('/add_chapter/<s_id>',methods=['POST'])
@login_required
@role_required('admin')
def add_chapter(s_id):
    chapter_name = request.form['chapter_name']
    description = request.form['description']
    id = 'C' + str(uuid.uuid4().hex[:8])

    new_chapter = Chapter(chp_id=id, chp_name=chapter_name, chp_desc=description, sub_id=s_id)
    db.session.add(new_chapter)
    db.session.commit()
    
    return redirect(request.referrer)

@main.route('/subject_details/<sub_id>')
@login_required
@role_required('admin')
def subject_details(sub_id):
    sub = Subject.query.filter_by(sub_id=sub_id).first()
    chap = Chapter.query.filter_by(sub_id=sub_id).all()
    return render_template('admin_subject.html', sub=sub, chapters=chap)

@main.route('/edit_subject/<s_id>',methods=['POST'])
@login_required
@role_required('admin')
def edit_subject(s_id):
    sub = Subject.query.filter_by(sub_id=s_id).first()
    sub.sub_name=request.form['subject_name']
    sub.sub_desc=request.form['description']

    db.session.commit()
    return redirect(request.referrer)

@main.route('/delete_subject/<s_id>',methods=['POST'])
@login_required
@role_required('admin')
def delete_subject(s_id):
    sub = Subject.query.filter_by(sub_id=s_id).first()
    db.session.delete(sub)
    db.session.commit()
    flash('Subject deleted !!',"success")
    return redirect(request.referrer)

@main.route('/add_question/<sub>/<chapter>/<quiz>',methods=['GET','POST'])
@login_required
@role_required('admin')
def add_question(sub,chapter,quiz):
    statement=request.form['statement']
    option1=request.form['option1']
    option2=request.form['option2']
    option3=request.form['option3']
    option4=request.form['option4']
    answer=request.form['correctAnswer']
    id = 'Q' + str(uuid.uuid4().hex[:8])
    option={'1': option1, '2': option2, '3': option3, '4': option4}

    ques=Question(ques_id=id,sub_id=sub,chp_id=chapter,q_id=quiz,statement=statement,options=option,answer=answer)
    db.session.add(ques)
    db.session.commit()
    return redirect(request.referrer)

@main.route('/quizzes/<subject>/<chap>',methods=['GET','POST'])
@login_required
def quiz_list(subject,chap):
    sub=Subject.query.filter_by(sub_id=subject).first()
    chapter=Chapter.query.get(chap)
    quiz_list=Quiz.query.filter_by(chp_id=chap).all()
    if session.get('user_type') == 'admin':
        return render_template('quiz_list.html',sub=sub,chapter=chapter, quiz_list=quiz_list)
    else:
        return render_template('quiz_list_user.html',sub=sub,chapter=chapter, quiz_list=quiz_list, today_date=date.today())

@main.route('/add_quiz/<sub>/<chapter>', methods=['GET','POST'])
@login_required
@role_required('admin')
def add_quiz(sub,chapter):
    quiz_name=request.form['quiz_name']
    quiz_date_str=request.form['quiz_date']
    quiz_duration_str=request.form['quiz_duration']
    quiz_id = 'Qz' + str(uuid.uuid4().hex[:8])

    try:
        quiz_date = datetime.strptime(quiz_date_str, '%Y-%m-%d').date()
    except ValueError:
        flash("Invalid date format. Use YYYY-MM-DD.")
        return redirect(request.referrer)
    
    minutes = int(quiz_duration_str)
    quiz_duration = time(hour=minutes // 60, minute=minutes % 60)

    quiz=Quiz(q_id=quiz_id, q_name=quiz_name, chp_id=chapter, sub_id=sub, date_of_quiz=quiz_date, time_dur=quiz_duration)

    db.session.add(quiz)
    db.session.commit()
    return redirect(request.referrer)

@main.route('/questions/<subject>/<chap>/<quiz>',methods=['GET','POST'])
@login_required
def questions(subject,chap,quiz):
    ques_list=Question.query.filter_by(q_id=quiz).all()
    sub=Subject.query.filter_by(sub_id=subject).first()
    chapter=Chapter.query.get(chap)
    quiz=Quiz.query.filter_by(q_id=quiz).first()
    if session.get('user_type') == 'admin':
        return render_template('question_list.html',questions=ques_list,sub=sub,chapter=chapter,quiz=quiz)
    else:
        return render_template('question_list_user.html',questions=ques_list,sub=sub,chapter=chapter,quiz=quiz)

@main.route('/delete_chapter/<chap>',methods=['GET','POST'])
@login_required
@role_required('admin')
def delete_chapter(chap):
    chapter=Chapter.query.filter_by(chp_id=chap).first()
    db.session.delete(chapter)
    db.session.commit()
    return redirect(request.referrer)

@main.route('/edit_chapter/<chap>',methods=['GET','POST'])
@login_required
@role_required('admin')
def edit_chapter(chap):
    chapter=Chapter.query.filter_by(chp_id=chap).first()
    chapter.chp_name=request.form['chapter_name']
    chapter.chp_desc=request.form['description']
    db.session.commit()
    return redirect(request.referrer)

@main.route('/delete_ques/<ques>',methods=['GET','POST'])
@login_required
@role_required('admin')
def delete_ques(ques):
    question=Question.query.filter_by(ques_id=ques).first()
    db.session.delete(question)
    db.session.commit()
    return redirect(request.referrer)

@main.route('/edit_ques/<question>',methods=['GET','POST'])
@login_required
@role_required('admin')
def edit_ques(question):
    ques=Question.query.filter_by(ques_id=question).first()
    ques.statement=request.form['statement']

app/templates/admin_home.html
{% extends 'layout.html' %}

{% block title %}
Admin
{% endblock %}

{% block content %}
<div class="mt-5 mb-3 subjects">
{% for subject in subject_list %}
<div class="sub_card">
<h4 class="subject-heading">
  <a href="{{ url_for('main.subject_details',sub_id=subject.sub_id) }}" style="color: black; text-decoration: none ;">
    {{ subject.sub_name }}
  </a>
</h4>
<div>
<p><strong >{{ subject.sub_desc }}</strong></p>
  Number of Chapter : 
  {{ chap | selectattr('sub_id', 'equalto', subject.sub_id) | list | length }}<br>
</div>
<div class="buttons">
  <button class="btn btn-outline-warning"  data-toggle="modal" data-target="#editSubject{{subject.sub_id}}">Edit</button>
  <a class="btn btn-outline-danger" data-toggle="modal" data-target="#deleteSubject{{subject.sub_id}}">Delete</a>
  <a class="btn btn-outline-info" href="{{ url_for('main.subject_details',sub_id=subject.sub_id) }}">Open</a>
</div>

<div class="modal" tabindex="-1" role="dialog" id="deleteSubject{{subject.sub_id}}">
  <div class="modal-dialog" role="document">
    <form method="POST" action="{{ url_for('main.delete_subject', s_id=subject.sub_id) }}">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" style="color: red;">Delete Subject!!</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p style="color: rgb(210, 86, 86);">Are you sure you want to delete the subject?</p>
        </div>
        <div class="modal-footer">
          <button type="submit" class="btn btn-danger">Yes</button>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
        </div>
      </div>
    </form>
  </div>
</div>


<div class="modal fade" id="editSubject{{subject.sub_id}}" tabindex="-1" role="dialog" aria-labelledby="editSubjectLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="editSubjectLabel">Edit Subject</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form id="editSubjectForm{{subject.sub_id}}" method="POST" action="{{ url_for('main.edit_subject',s_id=subject.sub_id) }}">
          <div class="form-group">
            <label for="subjectName{{subject.sub_id}}">Subject Name</label>
            <input type="text" class="form-control" value="{{subject.sub_name}}" id="subjectName{{subject.sub_id}}" name="subject_name" required>
          </div>
          <div class="form-group">
              <label for="subject_desc{{subject.sub_id}}">Description</label>
              <input type="text" class="form-control" value="{{subject.sub_desc}}" id="subject_desc{{subject.sub_id}}" name="description" required>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="submit" form="editSubjectForm{{subject.sub_id}}" class="btn btn-primary">Save</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
</div>
{% endfor %}
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover shadow-sm">
      <thead class="table-info">
          <tr class="text-center">
              <th>S_No.</th>
              <th>User Name</th>
              <th>User Type</th>
              <th>Qualification</th>
              <th>Date Of Birth</th>
              <th>Action</th>
          </tr>
      </thead>
      <tbody>
          {% if user_list %}
          {% for user in user_list %}
              <tr>
                  <td>{{ loop.index }}</td>
                  <td>{{ user.user_name }}</td>
                  <td>{{ user.user_type }}</td>
                  <td>{{ user.qualification }}</td>
                  <td>{{ user.dob }}</td>
                  <td>
                    <button class="btn btn-outline-danger" data-toggle="modal" data-target="#removeUser{{user.user_id}}">Remove</button>
                  </td>
              </tr>

              <div class="modal" tabindex="-1" role="dialog" id="removeUser{{user.user_id}}">
                <div class="modal-dialog" role="document">
                  <form method="POST" action="{{ url_for('main.remove_user', user=user.user_id) }}">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" style="color: red;">Remove User!!</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <div class="modal-body">
                        <p style="color: rgb(210, 86, 86);">Are you sure you want to Remove the User?</p>
                      </div>
                      <div class="modal-footer">
                        <button type="submit" class="btn btn-danger">Yes</button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                      </div>
                    </div>
                  </form>
                </div>
              </div>
          {% endfor %}
          {% else %}
              <tr>
                  <td colspan="6" class="text-muted fs-5">No registration yet</td>
              </tr>
          {% endif %}
      </tbody>
  </table>
</div>

<div class="fab-container justify-content-center">
  <button class="fab" data-toggle="modal" data-target="#newSubjectModal">
    <i class="fas fa-plus fa-lg"></i> S u b j e c t 
  </button>
</div>

<div class="modal fade" id="newSubjectModal" tabindex="-1" role="dialog" aria-labelledby="newSubjectModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="newSubjectModalLabel">Add New Subject</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form id="newSubjectForm" method="POST" action="{{ url_for('main.add_subject') }}">
          <div class="form-group">
            <label for="subjectName">Subject Name</label>
            <input type="text" class="form-control" id="SubjectName" name="subject_name" required>
          </div>
          <div class="form-group">
              <label for="subjectName">Description</label>
              <input type="text" class="form-control" id="description" name="description" required>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="submit" form="newSubjectForm" class="btn btn-primary">Save</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block style %}
<style>
.subjects {
  display: flex;
  flex-wrap: wrap;
  margin-top: 200px;
  gap: 20px;
  text-align: center;
  width: 1100px;
  margin: auto;
}

.sub_card {
  width: calc(25% - 20px);
  border: 2px solid grey;
  border-radius: 5px;
  margin-bottom: 10px;
  text-align: left;
  padding: 10px;
  display: flex;
  flex-direction: column;
  justify-content: space-between;
}

.buttons{
  border-top: 2px solid ;
  padding-top: 5px;
  display: flex;
  justify-content: space-between;
}

.subject-heading {
  font-weight:bold;
  margin-bottom: 10px;
  padding-bottom: 5px;
  border-bottom: 2px solid ;
}

.fab-container {
  position: fixed;
  bottom: 100px;
  right: 30px;
}

.fab {
  background-color: white;
  color: rgba(255, 30, 0, 0.777);
  border:2px solid rgba(255, 30, 0, 0.777);
  border-radius: 50%;
  padding: 15px;
  font-size: 20px;
  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.2);
}

.fab:hover {
  background-color: rgba(255, 30, 0, 0.777);
  color: white;
  transform: translateY(-6px);
}

</style>
{% endblock %}

app/templates/admin_summary.html
{% extends 'layout.html' %}

{% block title %}
Admin Summary
{% endblock %}

{% block content %}
<div class="chart-container">
    <canvas id="subjectChart"></canvas>
</div>

<div class="chart-container mt-5">
    <canvas id="statsChart"></canvas>
</div>

<div class="chart-container mt-5">
    <canvas id="topQuizChart"></canvas>
</div>


{% endblock %}


{% block style %}
<style>
    .chart-container {
        width: 800px;
        height: 500px;
        margin: 0 auto;
    }
</style>

{% endblock %}

{% block script %}
<script>
    var ctx1 = document.getElementById('subjectChart').getContext('2d');
    var subjectChart = new Chart(ctx1, {
        type: 'bar',
        data: {
            labels: {{ subject_names | tojson }},
            datasets: [{
                label: 'Number of Quizzes per Subject',
                data: {{ quiz_counts | tojson }},
                backgroundColor: 'rgba(75, 192, 192, 0.5)',
                borderColor: 'rgba(75, 192, 192, 1)',
                borderWidth: 1
            }]
        },
        options: { responsive: true, scales: { y: { beginAtZero: true } } }
    });


    var ctx3 = document.getElementById('statsChart').getContext('2d');
    var statsChart = new Chart(ctx3, {
        type: 'pie',
        data: {
            labels: ['Users', 'Quizzes', 'Chapters'],
            datasets: [{
                label: 'Overall Summary',
                data: [{{ user_count }}, {{ quiz_count }}, {{ chapter_count }}],
                backgroundColor: ['#ff6384', '#36a2eb', '#ffcd56']
            }]
        },
        options: { responsive: true }
    });

    var ctx4 = document.getElementById('topQuizChart').getContext('2d');
    var topQuizChart = new Chart(ctx4, {
        type: 'bar',
        data: {
            labels: {{ quiz_names | tojson }},
            datasets: [{
                label: 'Number of Attempts',
                data: {{ quiz_attempts | tojson }},
                backgroundColor: 'rgba(255, 159, 64, 0.5)',
                borderColor: 'rgba(255, 159, 64, 1)',
                borderWidth: 1
            }]
        },
        options: { responsive: true, scales: { y: { beginAtZero: true } } }
    });
</script>

{% endblock %}

app/templates/index.html
{% extends 'layout.html' %}

{% block title %}
Quiz Master
{% endblock %}

{% block content %}
<div class="welcome" style="text-align: center">
    <div>
      <h2>Quiz Master</h2>
      <p>
        Welcome to our platform! Get the quizzes you are looking for and ace your subject.
      </p>
      <button class="btn btn-info btn-md" onclick="window.location.href='/login';">
        Login
      </button>
      <button class="btn btn-info btn-md" onclick="window.location.href='/register';">
        User Signup
      </button>
    </div>
  </div>
{% endblock %}

{% block style %}
<style>
    .welcome {
    background-color: rgb(200, 232, 232);
    margin: 72px auto;
    color: rgb(5, 127, 127); 
    padding: 20px 40px;
    border-radius: 10px;
    box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
    text-align: center;
    max-width: 400px;
}





.welcome button {
    margin: 5px;
    background-color: white; 
    color: rgb(5, 127, 127); 
    border: 1px solid rgb(5, 127, 127); 
}

</style>
{%endblock%}

app/templates/quiz_list.html
{% extends 'layout.html' %}

{% block title %}
Subject Details
{% endblock %}

{% block content %}
<div class="container mt-4">
    <div class="card shadow-lg p-4 mb-4 rounded">
        <div class="d-flex justify-content-between align-items-center">
            <div>
                <h1 class="fw-bold">{{ sub.sub_name }}</h1>
                <p class="text-muted fs-5">{{ chapter.chp_name }}</p>
            </div>
            <div>
                <button class="btn btn-info" data-toggle="modal" data-target="#addQuiz">Add Quiz</button>
                <div class="modal fade" id="addQuiz" tabindex="-1" role="dialog" aria-labelledby="addQuizLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h5 class="modal-title" id="addQuizLabel">Add New Quiz</h5>
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                          </button>
                        </div>
                        <div class="modal-body">
                          <form id="addQuizForm" method="POST" action="{{ url_for('main.add_quiz', sub=sub.sub_id, chapter=chapter.chp_id) }}">
                            <div class="form-group">
                              <label for="QuizName">Quiz Name</label>
                              <input type="text" class="form-control" id="QuizName" name="quiz_name" required>
                            </div>
                            <div class="form-group">
                                <label for="quizdate">Quiz Date</label>
                                <input type="date" class="form-control" id="quizdate" name="quiz_date" required>
                            </div>
                            <div class="form-group">
                                <label for="quizduration">Duration (in minutes)</label>
                                <input type="number" class="form-control" id="quizduration" placeholder="duration in minutes" name="quiz_duration" required>
                            </div>
                          </form>
                        </div>
                        <div class="modal-footer">
                          <button type="submit" form="addQuizForm" class="btn btn-primary">Save</button>
                          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        </div>
                      </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<div>
{% for quiz in quiz_list %}
<div class="d-flex justify-content-between shadow rounded-3 border p-3 mb-3">
  <div class="border-end pr-5"><div class="fs-5 fw-bold">Quiz Name</div>{{quiz.q_name}}</div>
  <div class="border-end pr-5"><div class="fs-5 fw-bold">Quiz Date</div>{{quiz.date_of_quiz.strftime('%d-%m-%Y')}}</div>
  <div class="border-end pr-5"><div class="fs-5 fw-bold">Duration</div>{{quiz.time_dur}}</div>
  <div class="d-flex justify-content-center align-items-center">
    <button class="btn btn-outline-info" data-toggle="modal" data-target="#addQuestion{{quiz.q_id}}">Add Questions</button>
    <a class="btn btn-outline-info ml-3" href="{{ url_for('main.questions',subject=sub.sub_id,chap=chapter.chp_id,quiz=quiz.q_id) }}">Open</a>
  </div>
</div>

<div class="modal fade" id="addQuestion{{quiz.q_id}}" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
          <div class="modal-header">
              <h5 class="modal-title">Add New Question</h5>
              <button type="button" class="close" data-dismiss="modal">
                  <span>&times;</span>
              </button>
          </div>
          <div class="modal-body">
              <form id="addQuestion{{quiz.q_id}}Form" method="POST" action="{{ url_for('main.add_question', sub=sub.sub_id, chapter=chapter.chp_id, quiz=quiz.q_id) }}">
                  <div class="mb-3">
                      <label class="form-label">Question Statement</label>
                      <input type="text" class="form-control" name="statement" required>
                  </div>
                  {% for i in range(1, 5) %}
                  <div class="mb-3">
                      <label class="form-label">Option {{ i }}</label>
                      <input type="text" class="form-control" name="option{{ i }}" required>
                  </div>
                  {% endfor %}
                  <div class="mb-3">
                      <label class="form-label">Correct Option</label>
                      <input type="text" class="form-control" name="correctAnswer" required>
                  </div>
              </form>
          </div>
          <div class="modal-footer">
              <button type="submit" form="addQuestion{{quiz.q_id}}Form" class="btn btn-success">Add</button>
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
      </div>
  </div>
</div>

{% endfor %}
</div>
</div>
{% endblock %}

{% block style %}
<style>
    body {
        background-color: white;
    }
    
    .card {
        border-left: 5px solid rgb(9, 120, 120);
    }
</style>
{% endblock %}

app/templates/user_reg.html
{% extends 'layout.html' %}

{% block title %}
Customer register
{% endblock %}

{% block content %}
<div id="box">
    <div></div>
    <div id="register" class="form-group row">
        <h1>Customer SignUp</h1>
        <form class="mt-4" method="post" action="{{url_for('main.register')}}">
            <label class="form-label" for="email">
            Email ID (Username):  <input class="form-control" id="email" name="email" type="email"/>
            </label>
            <label class="form-label" for="fullname">
            Fullname:  <input class="form-control" id="fullname" name="fullname" type="text"/>
            </label><br>
            <label class="form-label" for="password">
            Password:  <input type="password" class="form-control" id="password" name="password" type="text"/>
            </label>
            <label class="form-label" for="cpassword">
            Confirm Password:  <input type="password" class="form-control" id="cpassword" name="cpassword" type="text"/>
            </label><br>
            <label class="form-label" for="address">
            Qualification:  <input class="form-control" id="qualification" name="qualification" type="text"/>
            </label>
            <label class="form-label" for="dob">
            Date Of Birth:  <input class="form-control" id="dob" name="dob" type="date"/>
            </label><br>
            <button class="btn" type="submit" style="color: rgb(35, 124, 135) ; border-color: rgb(35, 124, 135) ; border-width: 2px;">Register</button>
        </form>
    </div>
    <div></div>
</div>
{% endblock %}

{% block style %}
<style>
    #register {
        
        display: flex;
        flex-direction: column;
        align-items: center;
    } 
    #box {
        display: flex;
        margin-top: 60px;
        justify-content: space-evenly;
        border: 3px solid rgb(5, 127, 127); 
        padding: 10px;
        border-radius: 10px;
        width: 50%;
        margin: 40px auto;
    }
</style>
{% endblock %}

app/templates/view_service.html
{% extends 'layout.html' %}

{% block title %}
service
{% endblock %}

{% block content %}
<h2>this is the service</h2>
<p>Name: {{ s.s_name }}</p>
<p>Description: {{ s.description }}</p>
<p>Base Price: {{ s.base_price }}</p>
{% endblock %}

{% block style %}
{% endblock %}